package Vistas;

import java.awt.Color;
import javax.swing.JInternalFrame;

public class menuPrincipal extends javax.swing.JFrame {

    private AltaHuesped altaHuesped;

    private boolean altaHuespedAbierta = false;


    public menuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFondo = new Recursos.JPanelRedondeado();
        jPMenu = new Recursos.JPanelRedondeado();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPHuesped = new Recursos.JPanelRedondeado();
        jLHuespued = new javax.swing.JLabel();
        jPAltaHuesped = new Recursos.JPanelRedondeado();
        jLAltaHuesped = new javax.swing.JLabel();
        jPModificacionHuesped = new Recursos.JPanelRedondeado();
        jLModificacionHuesped = new javax.swing.JLabel();
        jPBajaHuesped = new Recursos.JPanelRedondeado();
        jLBajaHuesped = new javax.swing.JLabel();
        jPHabitacion = new Recursos.JPanelRedondeado();
        jLHabitacion = new javax.swing.JLabel();
        jPAltaHabitacion = new Recursos.JPanelRedondeado();
        jLAltaHabitacion = new javax.swing.JLabel();
        jPModificacionHabitacion = new Recursos.JPanelRedondeado();
        jLModificacionHabitacion = new javax.swing.JLabel();
        jPBajaHabitacion = new Recursos.JPanelRedondeado();
        jLBajaHabitacion = new javax.swing.JLabel();
        jPReserva = new Recursos.JPanelRedondeado();
        jLReserva = new javax.swing.JLabel();
        jPAltaReserva = new Recursos.JPanelRedondeado();
        jLAltaReserva = new javax.swing.JLabel();
        jPModificacionReserva = new Recursos.JPanelRedondeado();
        jLModificacionReserva = new javax.swing.JLabel();
        jPBajaReserva = new Recursos.JPanelRedondeado();
        jLBajaReserva = new javax.swing.JLabel();
        jPCopyRight = new Recursos.JPanelRedondeado();
        jLCopyRight = new javax.swing.JLabel();
        jDPPrograma = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPFondo.setBackground(new java.awt.Color(230, 232, 235));

        jPMenu.setBackground(new java.awt.Color(230, 232, 235));
        jPMenu.setPreferredSize(new java.awt.Dimension(180, 746));
        jPMenu.setRoundBottomLeft(30);
        jPMenu.setRoundBottomRight(30);
        jPMenu.setRoundTopLeft(30);
        jPMenu.setRoundTopRight(30);

        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 4));

        jPHuesped.setBackground(new java.awt.Color(230, 232, 235));
        jPHuesped.setPreferredSize(new java.awt.Dimension(167, 30));
        jPHuesped.setRoundBottomLeft(20);
        jPHuesped.setRoundBottomRight(20);
        jPHuesped.setRoundTopLeft(20);
        jPHuesped.setRoundTopRight(20);

        jLHuespued.setBackground(new java.awt.Color(0, 0, 0));
        jLHuespued.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLHuespued.setForeground(new java.awt.Color(0, 0, 0));
        jLHuespued.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLHuespued.setText("Huesped");
        jLHuespued.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout jPHuespedLayout = new javax.swing.GroupLayout(jPHuesped);
        jPHuesped.setLayout(jPHuespedLayout);
        jPHuespedLayout.setHorizontalGroup(
            jPHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHuespedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLHuespued, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHuespedLayout.setVerticalGroup(
            jPHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLHuespued, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPAltaHuesped.setBackground(new java.awt.Color(230, 232, 235));
        jPAltaHuesped.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        jPAltaHuesped.setRoundBottomLeft(20);
        jPAltaHuesped.setRoundBottomRight(20);
        jPAltaHuesped.setRoundTopLeft(20);
        jPAltaHuesped.setRoundTopRight(20);
        jPAltaHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPAltaHuespedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPAltaHuespedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPAltaHuespedMouseExited(evt);
            }
        });

        jLAltaHuesped.setBackground(new java.awt.Color(0, 0, 0));
        jLAltaHuesped.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLAltaHuesped.setForeground(new java.awt.Color(0, 0, 0));
        jLAltaHuesped.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLAltaHuesped.setText("Alta");
        jLAltaHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAltaHuespedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLAltaHuespedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLAltaHuespedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPAltaHuespedLayout = new javax.swing.GroupLayout(jPAltaHuesped);
        jPAltaHuesped.setLayout(jPAltaHuespedLayout);
        jPAltaHuespedLayout.setHorizontalGroup(
            jPAltaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAltaHuespedLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLAltaHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAltaHuespedLayout.setVerticalGroup(
            jPAltaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLAltaHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPModificacionHuesped.setBackground(new java.awt.Color(230, 232, 235));
        jPModificacionHuesped.setRoundBottomLeft(20);
        jPModificacionHuesped.setRoundBottomRight(20);
        jPModificacionHuesped.setRoundTopLeft(20);
        jPModificacionHuesped.setRoundTopRight(20);

        jLModificacionHuesped.setBackground(new java.awt.Color(0, 0, 0));
        jLModificacionHuesped.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLModificacionHuesped.setForeground(new java.awt.Color(0, 0, 0));
        jLModificacionHuesped.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLModificacionHuesped.setText("Modificaion");

        javax.swing.GroupLayout jPModificacionHuespedLayout = new javax.swing.GroupLayout(jPModificacionHuesped);
        jPModificacionHuesped.setLayout(jPModificacionHuespedLayout);
        jPModificacionHuespedLayout.setHorizontalGroup(
            jPModificacionHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificacionHuespedLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLModificacionHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPModificacionHuespedLayout.setVerticalGroup(
            jPModificacionHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLModificacionHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPBajaHuesped.setBackground(new java.awt.Color(230, 232, 235));
        jPBajaHuesped.setRoundBottomLeft(20);
        jPBajaHuesped.setRoundBottomRight(20);
        jPBajaHuesped.setRoundTopLeft(20);
        jPBajaHuesped.setRoundTopRight(20);

        jLBajaHuesped.setBackground(new java.awt.Color(0, 0, 0));
        jLBajaHuesped.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLBajaHuesped.setForeground(new java.awt.Color(0, 0, 0));
        jLBajaHuesped.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLBajaHuesped.setText("Baja");

        javax.swing.GroupLayout jPBajaHuespedLayout = new javax.swing.GroupLayout(jPBajaHuesped);
        jPBajaHuesped.setLayout(jPBajaHuespedLayout);
        jPBajaHuespedLayout.setHorizontalGroup(
            jPBajaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBajaHuespedLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLBajaHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBajaHuespedLayout.setVerticalGroup(
            jPBajaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBajaHuespedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLBajaHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPHabitacion.setBackground(new java.awt.Color(230, 232, 235));
        jPHabitacion.setRoundBottomLeft(20);
        jPHabitacion.setRoundBottomRight(20);
        jPHabitacion.setRoundTopLeft(20);
        jPHabitacion.setRoundTopRight(20);

        jLHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        jLHabitacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLHabitacion.setText("Habitacion");

        javax.swing.GroupLayout jPHabitacionLayout = new javax.swing.GroupLayout(jPHabitacion);
        jPHabitacion.setLayout(jPHabitacionLayout);
        jPHabitacionLayout.setHorizontalGroup(
            jPHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHabitacionLayout.setVerticalGroup(
            jPHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLHabitacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPAltaHabitacion.setBackground(new java.awt.Color(230, 232, 235));
        jPAltaHabitacion.setRoundBottomLeft(20);
        jPAltaHabitacion.setRoundBottomRight(20);
        jPAltaHabitacion.setRoundTopLeft(20);
        jPAltaHabitacion.setRoundTopRight(20);

        jLAltaHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        jLAltaHabitacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLAltaHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLAltaHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLAltaHabitacion.setText("Alta");

        javax.swing.GroupLayout jPAltaHabitacionLayout = new javax.swing.GroupLayout(jPAltaHabitacion);
        jPAltaHabitacion.setLayout(jPAltaHabitacionLayout);
        jPAltaHabitacionLayout.setHorizontalGroup(
            jPAltaHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAltaHabitacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLAltaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAltaHabitacionLayout.setVerticalGroup(
            jPAltaHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLAltaHabitacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPModificacionHabitacion.setBackground(new java.awt.Color(230, 232, 235));
        jPModificacionHabitacion.setRoundBottomLeft(20);
        jPModificacionHabitacion.setRoundBottomRight(20);
        jPModificacionHabitacion.setRoundTopLeft(20);
        jPModificacionHabitacion.setRoundTopRight(20);

        jLModificacionHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        jLModificacionHabitacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLModificacionHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLModificacionHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLModificacionHabitacion.setText("Modificaion");

        javax.swing.GroupLayout jPModificacionHabitacionLayout = new javax.swing.GroupLayout(jPModificacionHabitacion);
        jPModificacionHabitacion.setLayout(jPModificacionHabitacionLayout);
        jPModificacionHabitacionLayout.setHorizontalGroup(
            jPModificacionHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificacionHabitacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLModificacionHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPModificacionHabitacionLayout.setVerticalGroup(
            jPModificacionHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLModificacionHabitacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPBajaHabitacion.setBackground(new java.awt.Color(230, 232, 235));
        jPBajaHabitacion.setRoundBottomLeft(20);
        jPBajaHabitacion.setRoundBottomRight(20);
        jPBajaHabitacion.setRoundTopLeft(20);
        jPBajaHabitacion.setRoundTopRight(20);

        jLBajaHabitacion.setBackground(new java.awt.Color(0, 0, 0));
        jLBajaHabitacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLBajaHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLBajaHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLBajaHabitacion.setText("Baja");

        javax.swing.GroupLayout jPBajaHabitacionLayout = new javax.swing.GroupLayout(jPBajaHabitacion);
        jPBajaHabitacion.setLayout(jPBajaHabitacionLayout);
        jPBajaHabitacionLayout.setHorizontalGroup(
            jPBajaHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBajaHabitacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLBajaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBajaHabitacionLayout.setVerticalGroup(
            jPBajaHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBajaHabitacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPReserva.setBackground(new java.awt.Color(230, 232, 235));
        jPReserva.setRoundBottomLeft(20);
        jPReserva.setRoundBottomRight(20);
        jPReserva.setRoundTopLeft(20);
        jPReserva.setRoundTopRight(20);

        jLReserva.setBackground(new java.awt.Color(0, 0, 0));
        jLReserva.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLReserva.setForeground(new java.awt.Color(0, 0, 0));
        jLReserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLReserva.setText("Reserva");

        javax.swing.GroupLayout jPReservaLayout = new javax.swing.GroupLayout(jPReserva);
        jPReserva.setLayout(jPReservaLayout);
        jPReservaLayout.setHorizontalGroup(
            jPReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPReservaLayout.setVerticalGroup(
            jPReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPAltaReserva.setBackground(new java.awt.Color(230, 232, 235));
        jPAltaReserva.setRoundBottomLeft(20);
        jPAltaReserva.setRoundBottomRight(20);
        jPAltaReserva.setRoundTopLeft(20);
        jPAltaReserva.setRoundTopRight(20);

        jLAltaReserva.setBackground(new java.awt.Color(0, 0, 0));
        jLAltaReserva.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLAltaReserva.setForeground(new java.awt.Color(0, 0, 0));
        jLAltaReserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLAltaReserva.setText("Alta");

        javax.swing.GroupLayout jPAltaReservaLayout = new javax.swing.GroupLayout(jPAltaReserva);
        jPAltaReserva.setLayout(jPAltaReservaLayout);
        jPAltaReservaLayout.setHorizontalGroup(
            jPAltaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAltaReservaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLAltaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAltaReservaLayout.setVerticalGroup(
            jPAltaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLAltaReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPModificacionReserva.setBackground(new java.awt.Color(230, 232, 235));
        jPModificacionReserva.setRoundBottomLeft(20);
        jPModificacionReserva.setRoundBottomRight(20);
        jPModificacionReserva.setRoundTopLeft(20);
        jPModificacionReserva.setRoundTopRight(20);

        jLModificacionReserva.setBackground(new java.awt.Color(0, 0, 0));
        jLModificacionReserva.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLModificacionReserva.setForeground(new java.awt.Color(0, 0, 0));
        jLModificacionReserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLModificacionReserva.setText("Modificaion");

        javax.swing.GroupLayout jPModificacionReservaLayout = new javax.swing.GroupLayout(jPModificacionReserva);
        jPModificacionReserva.setLayout(jPModificacionReservaLayout);
        jPModificacionReservaLayout.setHorizontalGroup(
            jPModificacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificacionReservaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLModificacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPModificacionReservaLayout.setVerticalGroup(
            jPModificacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLModificacionReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPBajaReserva.setBackground(new java.awt.Color(230, 232, 235));
        jPBajaReserva.setRoundBottomLeft(20);
        jPBajaReserva.setRoundBottomRight(20);
        jPBajaReserva.setRoundTopLeft(20);
        jPBajaReserva.setRoundTopRight(20);

        jLBajaReserva.setBackground(new java.awt.Color(0, 0, 0));
        jLBajaReserva.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLBajaReserva.setForeground(new java.awt.Color(0, 0, 0));
        jLBajaReserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLBajaReserva.setText("Baja");

        javax.swing.GroupLayout jPBajaReservaLayout = new javax.swing.GroupLayout(jPBajaReserva);
        jPBajaReserva.setLayout(jPBajaReservaLayout);
        jPBajaReservaLayout.setHorizontalGroup(
            jPBajaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBajaReservaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLBajaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBajaReservaLayout.setVerticalGroup(
            jPBajaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBajaReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPCopyRight.setBackground(new java.awt.Color(230, 232, 235));
        jPCopyRight.setRoundBottomLeft(20);
        jPCopyRight.setRoundBottomRight(20);
        jPCopyRight.setRoundTopLeft(20);
        jPCopyRight.setRoundTopRight(20);

        jLCopyRight.setBackground(new java.awt.Color(0, 0, 0));
        jLCopyRight.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLCopyRight.setForeground(new java.awt.Color(0, 0, 0));
        jLCopyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCopyRight.setText("©  PULPCorp");

        javax.swing.GroupLayout jPCopyRightLayout = new javax.swing.GroupLayout(jPCopyRight);
        jPCopyRight.setLayout(jPCopyRightLayout);
        jPCopyRightLayout.setHorizontalGroup(
            jPCopyRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCopyRightLayout.createSequentialGroup()
                .addComponent(jLCopyRight, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPCopyRightLayout.setVerticalGroup(
            jPCopyRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCopyRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPAltaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPModificacionReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBajaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(jPBajaHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPModificacionHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPAltaHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(jPAltaHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPModificacionHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBajaHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jPHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPAltaHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPModificacionHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBajaHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPAltaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPModificacionHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBajaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPAltaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPModificacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBajaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jDPPrograma.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDPProgramaLayout = new javax.swing.GroupLayout(jDPPrograma);
        jDPPrograma.setLayout(jDPProgramaLayout);
        jDPProgramaLayout.setHorizontalGroup(
            jDPProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jDPProgramaLayout.setVerticalGroup(
            jDPProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDPPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDPPrograma)
                    .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLAltaHuespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAltaHuespedMouseClicked
        if (altaHuespedAbierta) {
            // La ventana está abierta, así que la cerramos
            altaHuesped.dispose();
            altaHuespedAbierta = false;
        } else {
            // La ventana está cerrada, así que la abrimos
            jDPPrograma.removeAll();
            jDPPrograma.repaint();
            // La ventana está cerrada, así que la abrimos
            centrarInternalFrame(altaHuesped);
            altaHuesped.setVisible(true);
            jDPPrograma.add(altaHuesped);
            //jPPrograma.moveToFront(altaHuesped);
            altaHuespedAbierta = true;

        }
    }//GEN-LAST:event_jLAltaHuespedMouseClicked

    private void jLAltaHuespedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAltaHuespedMouseEntered

        jPAltaHuesped.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_jLAltaHuespedMouseEntered

    private void jLAltaHuespedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAltaHuespedMouseExited

        jPAltaHuesped.setBackground(new Color(230, 232, 235));
    }//GEN-LAST:event_jLAltaHuespedMouseExited

    private void jPAltaHuespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAltaHuespedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPAltaHuespedMouseClicked

    private void jPAltaHuespedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAltaHuespedMouseEntered

        jPAltaHuesped.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jPAltaHuespedMouseEntered

    private void jPAltaHuespedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAltaHuespedMouseExited

        jPAltaHuesped.setBackground(new Color(230, 232, 235));
    }//GEN-LAST:event_jPAltaHuespedMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPPrograma;
    private javax.swing.JLabel jLAltaHabitacion;
    private javax.swing.JLabel jLAltaHuesped;
    private javax.swing.JLabel jLAltaReserva;
    private javax.swing.JLabel jLBajaHabitacion;
    private javax.swing.JLabel jLBajaHuesped;
    private javax.swing.JLabel jLBajaReserva;
    private javax.swing.JLabel jLCopyRight;
    private javax.swing.JLabel jLHabitacion;
    private javax.swing.JLabel jLHuespued;
    private javax.swing.JLabel jLModificacionHabitacion;
    private javax.swing.JLabel jLModificacionHuesped;
    private javax.swing.JLabel jLModificacionReserva;
    private javax.swing.JLabel jLReserva;
    private Recursos.JPanelRedondeado jPAltaHabitacion;
    private Recursos.JPanelRedondeado jPAltaHuesped;
    private Recursos.JPanelRedondeado jPAltaReserva;
    private Recursos.JPanelRedondeado jPBajaHabitacion;
    private Recursos.JPanelRedondeado jPBajaHuesped;
    private Recursos.JPanelRedondeado jPBajaReserva;
    private Recursos.JPanelRedondeado jPCopyRight;
    private Recursos.JPanelRedondeado jPFondo;
    private Recursos.JPanelRedondeado jPHabitacion;
    private Recursos.JPanelRedondeado jPHuesped;
    private Recursos.JPanelRedondeado jPMenu;
    private Recursos.JPanelRedondeado jPModificacionHabitacion;
    private Recursos.JPanelRedondeado jPModificacionHuesped;
    private Recursos.JPanelRedondeado jPModificacionReserva;
    private Recursos.JPanelRedondeado jPReserva;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
 private void centrarInternalFrame(JInternalFrame frame) {

        // Obtenemos el tamaño del JDesktopPane
        int anchoDesktop = jDPPrograma.getWidth();
        int altoDesktop = jDPPrograma.getHeight();

        // Obtenemos el tamaño del JInternalFrame
        int anchoFrame = frame.getWidth();
        int altoFrame = frame.getHeight();

        // Calculamos las coordenadas para centrar el JInternalFrame
        int x = (anchoDesktop - anchoFrame) / 2;
        int y = (altoDesktop - altoFrame) / 2;

        // Establecemos la ubicación del JInternalFrame
        frame.setLocation(x, y);
    }
}
